### ISSUE TITLE
npm run dev 报错

### ISSUE THREAD

**Issue by yongqi-zhang** [zyl1314/vue-forum#1]
windows 10操作系统
node/webpack/vue 版本都是当前最新
运行 npm run dev 报错
 ERROR  Failed to compile with 13 errors21:39:47

These dependencies were not found:

This relative module was not found:
第一次提 github 问题，如有表达问题请见谅，并留言，我会继续提供报错信息。

**Comment by zyl1314** [comment]
@yongqi-zhang 需要先安装依赖，npm install
